spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pictgram
    username: postgres
    password: postgres
    
  servlet:
    multipart:
     max-file-size: 20MB
     max-request-size: 20MB
image:
  local: true